import { useState } from "react";
import type { MeetingSummary } from "../types";
import { Empty } from "./Feedback";

export default function MeetingList({ meetings, query, onQuery, loading, hasMore, onMore, onOpen, visitor }: { meetings: MeetingSummary[]; query: string; onQuery: (value: string) => void; loading: boolean; hasMore: boolean; onMore: () => void; onOpen: (id: string) => void; visitor: boolean }) {
  const [grouped, setGrouped] = useState(false);
  const groups = [...new Set(meetings.map(meeting => meeting.title))].map(title => ({ title, rows: meetings.filter(meeting => meeting.title === title) }));
  function row(meeting: MeetingSummary) { return <li key={meeting.id}><button onClick={() => onOpen(meeting.id)}><strong>{meeting.title}</strong>{meeting.occurred_on && <span>Meeting date: {meeting.occurred_on}</span>}{meeting.created_at && <time dateTime={meeting.created_at}>Saved {new Date(meeting.created_at).toLocaleString()}</time>}<span>Revision {meeting.current_revision} · {meeting.visibility === "restricted" ? "Restricted access" : "Workspace access"}</span><code className="meeting-identifier">{meeting.id}</code></button></li>; }
  return <section className="panel meeting-list"><div className="section-heading"><div><h2>Your meetings</h2><p>Each saved identifier is a separate meeting. Matching titles are kept as distinct records.</p></div><button aria-pressed={grouped} onClick={() => setGrouped(value => !value)}>{grouped ? "Show individual meetings" : "Group matching titles"}</button></div><label>Find a meeting<input type="search" maxLength={200} value={query} onChange={event => onQuery(event.target.value)} placeholder="Meeting title or identifier" /></label><p className="muted" role="status">{loading ? "Searching permitted meetings…" : meetings.length + " meetings loaded"}{hasMore ? " · more records available" : ""}</p>{!meetings.length && !loading ? <Empty>{query ? "No permitted meetings match this title or identifier." : visitor ? "No examples opened yet. Choose a synthetic conversation above." : "Create a meeting or open a saved conversation. Saving an example as a new meeting creates a new identifier."}</Empty> : grouped ? <div className="meeting-groups">{groups.map(group => <details key={group.title}><summary>{group.title} · {group.rows.length} loaded record{group.rows.length === 1 ? "" : "s"}</summary><ul>{group.rows.map(row)}</ul></details>)}</div> : <ul>{meetings.map(row)}</ul>}{hasMore && <button disabled={loading} onClick={onMore}>Load more meetings</button>}</section>;
}
