import { useEffect, useState } from "react";
import { api, scoped } from "../api";
import type { Department, Kind, Meeting, Participant, Workspace } from "../types";
import { Empty, ErrorNotice } from "./Feedback";
import { kindNames, OutcomeCard } from "./OutcomeCard";
import GoogleMeetImport, { type ImportedMeeting } from "./GoogleMeetImport";

export function TranscriptStep(props: { meeting: Meeting | null; title: string; setTitle: (s: string) => void; text: string; setText: (s: string) => void; slug: string; setSlug: (s: string) => void; occurred: string; setOccurred: (s: string) => void; visibility: "workspace" | "restricted"; setVisibility: (s: "workspace" | "restricted") => void; editable: boolean; pending: boolean; dirty: boolean; onSubmit: (e: React.FormEvent) => void; onUpload: (file?: File) => void; onExample: () => void; onContinue: () => void; department: Department; workspace?: Workspace; onImported?: (value: ImportedMeeting) => Promise<void> }) {
  const p = props;
  return <section className="panel step-panel"><span className="eyebrow">Step 1 of 4</span><h1>Bring the conversation.</h1><p>Paste a written transcript, upload a text file, or try the department example.</p>
    {!p.meeting && <div className="transcript-sources"><button type="button" disabled={!p.editable || p.pending} onClick={p.onExample}>Load synthetic {p.department} example</button><label className="file-label">Upload a transcript<input type="file" disabled={!p.editable || p.pending} accept=".txt,.md,text/plain,text/markdown" onChange={e => p.onUpload(e.target.files?.[0])} /></label>{p.workspace && p.onImported && <GoogleMeetImport workspace={p.workspace} meetingId={p.slug} title={p.title} visibility={p.visibility} disabled={!p.editable || p.pending} beforeSave={() => !p.text.trim() || window.confirm("Save this Google transcript and discard the unsaved text currently in the editor?")} onImported={p.onImported} />}</div>}
    <form onSubmit={p.onSubmit}><fieldset disabled={!p.editable || p.pending}><legend className="sr-only">Transcript details</legend>
      <label>Meeting title<input value={p.title} required maxLength={200} onChange={e => p.setTitle(e.target.value)} placeholder="What was the meeting about?" /></label>
      <label>Transcript text<textarea required maxLength={1_000_000} rows={9} value={p.text} onChange={e => p.setText(e.target.value)} placeholder="Alex: We need to prepare the onboarding checklist by Monday." /></label>
      {!p.meeting && <div className="form-grid"><label>Meeting date <span className="muted">(optional)</span><input type="date" value={p.occurred} onChange={e => p.setOccurred(e.target.value)} /></label><label>Who can access this meeting?<select value={p.visibility} onChange={e => p.setVisibility(e.target.value as typeof p.visibility)}><option value="workspace">Workspace members</option><option value="restricted">Creator, owners and reviewers</option></select></label></div>}
      <details className="advanced"><summary>Advanced meeting settings</summary><label>Meeting identifier<input value={p.slug} required pattern="[A-Za-z0-9][A-Za-z0-9_.-]{0,127}" maxLength={128} disabled={Boolean(p.meeting)} onChange={e => p.setSlug(e.target.value)} /></label><p className="muted">A unique identifier is generated automatically. Keep it unless you need a specific reference.</p></details>
      {(p.dirty || !p.meeting) && <div className="step-actions"><button className="primary" disabled={!p.text.trim() || !p.title.trim() || !p.slug || !p.dirty}>{p.meeting ? "Save revision and continue" : "Save transcript and continue"}</button></div>}
    </fieldset></form>{p.meeting && !p.dirty && <div className="step-actions"><button className="primary" type="button" disabled={p.pending} onClick={p.onContinue}>Continue to people</button></div>}{p.dirty && <p role="status" className="muted">Unsaved transcript changes.</p>}
  </section>;
}

export function PeopleStep({ meeting, people, workspace, pending, ready, onExtract, onConfirm, onParticipantAdded, onDirty, onBack, onContinue, directoryEditable = true }: { meeting: Meeting; people: Participant[]; workspace: Workspace; pending: boolean; ready: boolean; onExtract: () => void; onConfirm: (mention: string, person: string) => void; onParticipantAdded: () => Promise<void>; onDirty: (id: string, dirty: boolean) => void; onBack: () => void; onContinue: () => void; directoryEditable?: boolean }) {
  const [name, setName] = useState(""), [role, setRole] = useState(""), [error, setError] = useState<unknown>(null), [adding, setAdding] = useState(false);
  const editable = workspace.role !== "viewer", unconfirmed = meeting.mentions.filter(m => !m.confirmed).length;
  useEffect(() => { onDirty("participant-form", Boolean(name || role)); return () => onDirty("participant-form", false); }, [name, role, onDirty]);
  async function add(event: React.FormEvent) {
    event.preventDefault(); setAdding(true); setError(null);
    try { await api(scoped(workspace.id, "/participants"), { method: "POST", body: JSON.stringify({ name, role, aliases: [] }) }); setName(""); setRole(""); await onParticipantAdded(); } catch (e) { setError(e); } finally { setAdding(false); }
  }
  return <section className="panel step-panel"><span className="eyebrow">Step 2 of 4</span><h1>Put people in context.</h1><p>Find the draft outcomes, then confirm who the transcript names refer to. Unconfirmed people can stay unassigned.</p><p className="muted">Transcript indexing {meeting.index_status}</p>
    <button disabled={!editable || !ready || pending || adding} onClick={onExtract}>{meeting.tasks.length ? "Extract outcomes again" : "Extract outcomes"}</button>
    {meeting.mentions.length ? <ul className="mentions">{meeting.mentions.map(mention => <MentionRow key={mention.id + ":" + String(mention.confirmed)} mention={mention} people={people} editable={editable && !pending && !adding} onConfirm={id => onConfirm(mention.id, id)} />)}</ul> : <Empty>{pending ? "Preparing the transcript and outcomes…" : "Extract outcomes to find participant suggestions. You can also add directory context below."}</Empty>}
    {editable && directoryEditable && <details><summary>Add a person to this workspace</summary><form onSubmit={add}><fieldset disabled={adding || pending}><legend className="sr-only">Add participant</legend><div className="form-grid"><label>Participant name<input required value={name} maxLength={120} onChange={e => setName(e.target.value)} /></label><label>Responsibilities<input value={role} maxLength={160} onChange={e => setRole(e.target.value)} /></label></div><button disabled={!name.trim()}>Add participant</button></fieldset></form><ErrorNotice error={error} /></details>}
    <p className="muted">Use People and Connections in the workspace menu for profile links and your own LinkedIn connection.</p>
    <div className="step-actions"><button onClick={onBack}>Back to transcript</button><button className="primary" disabled={!ready || pending || adding} onClick={onContinue}>{unconfirmed ? "Continue with unassigned people" : "Continue to review"}</button></div>
  </section>;
}

function MentionRow({ mention, people, editable, onConfirm }: { mention: Meeting["mentions"][number]; people: Participant[]; editable: boolean; onConfirm: (id: string) => void }) {
  const [person, setPerson] = useState(mention.participant_id || "");
  return <li><div><strong>{mention.name}</strong><small>{mention.confirmed ? "Confirmed directory match" : mention.candidates.length > 1 ? "Ambiguous name: multiple directory matches" : mention.candidates.length === 1 ? "One suggested match; confirmation required" : "No confirmed match yet"}</small></div><label>Directory match for {mention.name}<select value={person} disabled={!editable} onChange={e => setPerson(e.target.value)}><option value="">Leave unassigned</option>{people.map(p => <option value={p.id} key={p.id}>{p.name} · {p.role || "Participant"}</option>)}</select></label><button disabled={!person || !editable || (mention.confirmed && person === mention.participant_id)} onClick={() => onConfirm(person)}>Confirm person</button></li>;
}

export function ReviewStep({ meeting, people, workspace, pending, onDirty, onSaved, changeReview, onBack, onContinue, focusItem }: { meeting: Meeting; people: Participant[]; workspace: Workspace; pending: boolean; onDirty: (id: string, dirty: boolean) => void; onSaved: () => void; changeReview: (action: () => void) => void; onBack: () => void; onContinue: () => void; focusItem?: string }) {
  const [filter, setFilter] = useState<Kind | "all">("all"), [active, setActive] = useState("");
  const [savedAt, setSavedAt] = useState<number | null>(null);
  const focusAvailable = Boolean(focusItem && meeting.tasks.some(item => item.id === focusItem));
  useEffect(() => { if (focusItem && focusAvailable) { setFilter("all"); setActive(focusItem); } }, [focusItem, focusAvailable, meeting.id]);
  useEffect(() => { if (savedAt === null) return; const timer = setTimeout(() => setSavedAt(null), 900); return () => clearTimeout(timer); }, [savedAt]);
  const order: Kind[] = ["action", "decision", "blocker", "follow_up", "risk"];
  const items = meeting.tasks.filter(item => filter === "all" || item.kind === filter).sort((a, b) => order.indexOf(a.kind) - order.indexOf(b.kind) || a.id.localeCompare(b.id)), item = items.find(value => value.id === active) || items[0];
  const itemIds = items.map(value => value.id).join(",");
  useEffect(() => { if (!items.some(value => value.id === active)) setActive(previous => items.some(value => value.id === previous) ? previous : items[0]?.id || ""); }, [itemIds, active]);
  const position = item ? items.indexOf(item) : -1, approved = meeting.tasks.filter(value => value.status === "approved").length;
  return <section className="step-panel"><span className="eyebrow">Step 3 of 4 · Review</span>{savedAt !== null && <div className="save-spark" role="status" key={savedAt}><span aria-hidden="true">✦</span>Review saved.</div>}<h1>Review what matters.</h1><p>Check the evidence, owner and date for each outcome. {approved} of {meeting.tasks.length} approved.</p>
    <details className="review-filter"><summary>Filter outcomes</summary><label>Outcome type<select value={filter} onChange={e => changeReview(() => { setFilter(e.target.value as typeof filter); setActive(""); })}><option value="all">All types</option>{Object.entries(kindNames).map(([kind, name]) => <option key={kind} value={kind}>{name}</option>)}</select></label></details>
    {item && <label className="mobile-outcome-picker">Outcome to review<select value={item.id} disabled={pending} onChange={e => changeReview(() => setActive(e.target.value))}>{items.map(value => <option key={value.id} value={value.id}>{kindNames[value.kind]}: {value.title}</option>)}</select></label>}
    {item ? <><div className="review-layout"><nav aria-label="Outcomes to review"><ul>{items.map(value => <li key={value.id}><button disabled={pending} className={value.id === item.id ? "active" : ""} aria-current={value.id === item.id ? "true" : undefined} onClick={() => changeReview(() => setActive(value.id))}><span>{kindNames[value.kind]} · {value.status}</span><strong>{value.title}</strong></button></li>)}</ul></nav><div><p className="muted" role="status">Outcome {position + 1} of {items.length}</p><OutcomeCard key={item.id + ":" + item.version} item={item} participants={people} workspace={workspace} meetingId={meeting.id} onDirty={onDirty} onSaved={() => { setSavedAt(Date.now()); onSaved(); }} selected={false} onSelect={() => {}} selectable={false} /><div className="actions"><button disabled={position <= 0 || pending} onClick={() => changeReview(() => setActive(items[position - 1].id))}>Previous outcome</button><button disabled={position >= items.length - 1 || pending} onClick={() => changeReview(() => setActive(items[position + 1].id))}>Next outcome</button></div></div></div></> : <Empty>{meeting.tasks.length ? "No outcomes match this filter." : "No outcomes found yet. Return to People to extract, or update the transcript."}</Empty>}
    <div className="step-actions"><button onClick={onBack}>Back to people</button><button className="primary" disabled={pending} onClick={onContinue}>Continue to handoff</button></div>
  </section>;
}

export function MeetingHistory({ meeting, workspace, onArchive }: { meeting: Meeting; workspace: Workspace; onArchive: () => void }) {
  const [query, setQuery] = useState(""), [hits, setHits] = useState<{ text: string; metadata: { i: number; start_line: number }; score: number }[]>([]), [past, setPast] = useState<{ number: number; raw_text: string; tasks: Meeting["tasks"] } | null>(null), [error, setError] = useState<unknown>(null);
  async function search(e: React.FormEvent) { e.preventDefault(); try { const result = await api<{ results: typeof hits }>(scoped(workspace.id, "/meetings/" + meeting.id + "/search"), { method: "POST", body: JSON.stringify({ q: query, k: 5 }) }); setHits(result.results); } catch (e) { setError(e); } }
  async function revision(number: number) { try { setPast(await api(scoped(workspace.id, "/meetings/" + meeting.id + "/revisions/" + number))); } catch (e) { setError(e); } }
  return <details className="panel"><summary>Transcript history and evidence search</summary><form onSubmit={search}><label>Search transcript context<input value={query} maxLength={500} onChange={e => setQuery(e.target.value)} /></label><button disabled={!query.trim() || meeting.index_status !== "ready"}>Search evidence</button></form>{hits.map((hit, i) => <blockquote key={i}><cite>Chunk {hit.metadata.i + 1} · line {hit.metadata.start_line}</cite><p>{hit.text}</p></blockquote>)}<div className="actions">{meeting.revisions.map(row => <button key={row.id} onClick={() => revision(row.number)}>View transcript v{row.number}</button>)}{["owner", "reviewer"].includes(workspace.role) && <button onClick={onArchive}>Archive meeting</button>}</div><ErrorNotice error={error} />{past && <details open><summary>Transcript revision {past.number} · read only · {past.tasks.length} outcomes retained</summary><pre>{past.raw_text}</pre><ul>{past.tasks.map(item => <li key={item.id}>{item.title} · {item.status} · review v{item.version}</li>)}</ul></details>}</details>;
}
