import { lazy, Suspense, useState } from "react";
import { settingsPath, settingsSections, type SettingsSection } from "../navigation";
import type { User, Workspace } from "../types";
import type { useShellChrome } from "./ShellChrome";
import { ErrorNotice } from "./Feedback";

const Directory = lazy(() => import("./Directory")), Integrations = lazy(() => import("./Integrations")), Administration = lazy(() => import("./Administration")), PrivacyPage = lazy(() => import("./PrivacyPage"));
const labels: Record<SettingsSection, string> = { people: "People", connections: "Connections", privacy: "Privacy & data", access: "Access", motion: "Motion & layout" };
export default function SettingsPage({ workspaceId, workspace, user, section, navigate, onDirty, refreshUser, onAccountErased, motion, chrome }: { workspaceId: string; workspace?: Workspace; user: User; section: SettingsSection; navigate: (path: string) => void; onDirty: (value: boolean) => void; refreshUser: () => Promise<void>; onAccountErased: () => void; motion: { calm: boolean; reduced: boolean; toggle: () => void }; chrome: ReturnType<typeof useShellChrome> }) {
  const available = settingsSections.filter(value => !user.is_visitor || ["people", "connections", "motion"].includes(value));
  const [error, setError] = useState<unknown>(null);
  return <div className="settings-page"><div className="section-heading"><div><span className="eyebrow">Your workspace controls</span><details><summary>About workspace settings</summary><p>People, tools and preferences live here. Your meeting stays focused on its next step.</p></details></div></div><nav className="settings-sections" aria-label="Settings sections">{available.map(value => <a key={value} href={settingsPath(workspaceId, value)} aria-current={section === value ? "page" : undefined} onClick={event => { if (!event.ctrlKey && !event.metaKey && !event.shiftKey && event.button === 0) { event.preventDefault(); navigate(settingsPath(workspaceId, value)); } }}>{labels[value]}</a>)}</nav><ErrorNotice error={error} /><Suspense fallback={<p role="status">Loading settings…</p>}>{section === "motion" ? <section className="panel"><h1>Motion that follows your pace</h1><p>Calm mode keeps the same controls and information with a static presentation. Your system's reduced-motion preference takes priority.</p><button aria-pressed={motion.calm} disabled={motion.reduced} onClick={motion.toggle}>{motion.reduced ? "Reduced motion active" : motion.calm ? "Calm mode on" : "Enable calm mode"}</button><h3>Choose your workspace frame</h3><p>Layout controls stay available even when both regions are hidden.</p><div className="actions"><button aria-pressed={!chrome.sidebar} onClick={chrome.toggleSidebar}>{chrome.sidebar ? "Collapse sidebar" : "Expand sidebar"}</button><button aria-pressed={!chrome.header} onClick={chrome.toggleHeader}>{chrome.header ? "Collapse header" : "Expand header"}</button></div></section> : section === "privacy" ? user.is_visitor ? <p role="alert">Private account controls require an invited account. Demo reviews and plans belong to your temporary synthetic session.</p> : <PrivacyPage workspaceId={workspaceId} user={user} onWorkspaceChanged={refreshUser} onAccountErased={onAccountErased} /> : !workspace ? <p role="alert">This workspace is not available to your account. Choose an accessible workspace.</p> : section === "people" ? <Directory workspace={workspace} user={user} onDirty={onDirty} /> : section === "connections" ? <Integrations workspace={workspace} user={user} refreshUser={() => { void refreshUser().catch(setError); }} /> : user.is_visitor ? <p role="alert">Invitations and account administration are available in private workspaces.</p> : workspace.role === "owner" ? <Administration workspace={workspace} /> : <section className="panel"><h1>Your access</h1><p>Your current role is {workspace.role}. Only workspace owners manage invitations and membership roles. Reviewers approve outcomes and delivery; editors prepare source and draft changes; viewers read permitted content.</p></section>}</Suspense></div>;
}
